Disabled clippy linter in the handle_read function
This is because clippy recommended to use read_exact in the handle_read function but there are cases where the buffer is not filled and then the server panics with this message: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: UnexpectedEof, message: "failed to fill whole buffer" }'